### ISSUE TITLE
Introduce a FieldMapFromStruct() to avoid repetitions?

### ISSUE THREAD

**Issue by wmark** [mholt/binding#18]
What can we add to avoid repetitions such as this?
https://gist.github.com/wmark/73ee2abe30e13af93a18#file-mailgun-go-L3-L57

A ```FieldMapFromStruct()``` could use *reflection* to generate the [FieldMap](https://github.com/mholt/binding/blob/cb6c28ac11daf4a8a0ad10cbda1d38041b126d9b/binding.go#L689) from tags(?). Because this has to be done once only, for example during the module's ```init()``` I believe it wouldn't count towards the claim *Binding* was »reflectionless«.

**Comment by bhcleek** [comment]
Now that Go 1.4 is out, perhaps it would be better to provide a generator?
