### ISSUE TITLE
dynamic (runtime) FieldMap()

### ISSUE THREAD

**Issue by troyk** [mholt/binding#19]
use case: I'm using a 3rd party service that posts a resource to my application using application/x-www-form-urlencoded with camelcase names and as application/json with snakecase names depending (form encoded when the resource is created on their system and json when the resource is modified).  I'm not advocating this is a smart thing to do, but it exists in the wild none-the-less.

Currently, I used struct composition to use the same struct, but I have a very duplicated FieldMap.  I noticed Validate takes *http.Request as a param, but FieldMap does not.  If FieldMap also passed the http.Request that would solve my issue, but break the api.

Another idea would be to add a BindFn method so passing any  func()binding.FieldMap will satisfy and then the caller would be responsible for also calling validate.

Thoughts?

**Comment by mholt** [comment]
...6 months later

@troyk I've decided to modify FieldMap() so that it takes *http.Request as an argument. I think this should give the user any degree of liberty they need to take in order to make it work "in the wild" and the usage is still simple enough.

Instead of

```go
func (m *Model) FieldMap() FieldMap {
	return FieldMap{
		// ...
	}
}
```

it will look like

```go
func (m *Model) FieldMap(req *http.Request) FieldMap {
	return FieldMap{
		// ...
	}
}
```

The change will be pushed shortly. Please let me know if this is not sufficient or I misunderstood anything.

**Comment by bhcleek** [comment]
Unless I'm missing something, I don't understand why there @troyk has to create multiple structs. Json will bind correctly if you use `json` tags, and the FieldMapper's form field names should be what's sent when POSTing as application/x-www-form-urlencoded.

```go
type Foo struct {
    TitleCase `json:"title_case"`
}

func (f *Foo) FieldMap() binding.FieldMap {
  return FieldMap {
    &f.TitleCase: "titleCase",
  }
}
```

**Comment by mholt** [comment]
Ah! I had somehow missed that the one case was for form encoding and the other was for JSON data. Indeed, the two are orthogonal so that should work. (I should read more carefully.) @troyk can you confirm that solves your issue?

Even if it does, it's worth considering passing in the Request before locking down the API. Any objections?

**Comment by bhcleek** [comment]
I second @wmark's concern. I don't see any reason to pass it in, and if there is a need to pass it in, the client could simply use a closure.

**Comment by mholt** [comment]
@bhcleek How would you use a closure to access the request from the FieldMap method?

**Comment by bhcleek** [comment]
I don't know what I was thinking; obviously, the way binding uses a FieldMapper, a closure wouldn't work, but you could still do something like this:
```go
type mapper struct {
   r *http.Request
   Field1 int
}

func (m *mapper) FieldMap() binding.FieldMap {
   // do something here, using m.r
}

func Handle(w http.ResponseWriter, r *http.Request) {
   v := &mapper{
     r: r,
    }

    binding.Bind(r, v)
}
```

In short, if the FieldMapper needs state, then just associate the *http.Request with the FieldMapper before calling `binding.Bind`.

**Comment by mholt** [comment]
That also looks good to me. It allows you to get any kind of context you need in order to create the mapping.

Go is cool.

**Comment by troyk** [comment]
@mholt we've since drunken the context koolaid and our structs look like:
```go
func (f *form) Bind(ctx context.Context, params map[string]interface{}) error {
  f.SomeInt = coerce.Int(params["some_int"])
}

func (f *form) Validate(ctx context.Context) error {
}
```

We had to drop to map[string]interface{} (and we've been very happy with it) to keep backwards with our old API which was written in a dynamic language and does not care if an int from JSON is represented as "5" or 5.  And of course we send all sorts of state in the context and return error if the state is not present, etc .. hit the db from Validate etc.

But I agree with @bhcleek and if your moving towards breaking backwards compat for good cause it makes sense to remove `*http.Request` from Validate for all the same reasons as not to add it to Bind

And Go is very cool indeed!  Thanks for this lib!
