### ISSUE TITLE
Return error interface instead of Errors

### ISSUE THREAD

**Issue by troyk** [mholt/binding#22]
Would you be interested in a pull request to make the API more idiomatic.   The following code highlights the issue with returning the Errors type and how it goes against the grain and can cause hard to find runtime bugs.  Assume binding.Bind(c.Request, m)  is succesful

``` go
var err error
err = binding.Bind(c.Request, m)
log.Println(err == nil)  // false
```

``` go
err := binding.Bind(c.Request, m)
log.Println(err == nil)  // true
```

Both example compile, however because the first example is using an interface and Bind does not explicitly return nil on Empty errors it is using the result of Errors.String

**Comment by mholt** [comment]
@troyk Returning `error` instead of `binding.Errors` makes it hard to call `.Handle()` because you have to do a type assertion first, e.g. `if err.(binding.Errors).Handle()`.

I'm not opposed to this, I guess I just need more feedback - if lots of people would rather use the `err != nil` idiom then perhaps this would be a good thing to do. But if more people are just using `err.Handle()` like in the examples then I'd rather leave it as-is.

**Comment by bhcleek** [comment]
I'd rather see it return an error type, too. After using this package for a quite a while, I still find the error checking to be awkward. The package's use cases should support, as much as possible, writing idiomatic Go.

**Comment by mholt** [comment]
Okay. We can go that route then.

By the way, great to meet you at Gophercon. :) Glad you said hi.

**Comment by bhcleek** [comment]
It was good to meet you, too. Next year we should actually grab a beer or something.

Related to this issue, how would you feel about not exporting the error types, but instead implementing interfaces on them? Dave Cheney had an interesting blog post about this last year: http://dave.cheney.net/2014/12/24/inspecting-errors.

**Comment by bhcleek** [comment]
I've started this work, and should have something to review soon, unless @troyk is still interested submitting a patch.

**Comment by mholt** [comment]
I'm interested to see what you come up with. I've been experimenting too (really, I have!) but nothing to show quite yet.

**Comment by troyk** [comment]
@bhcleek it's all you guys, would love to contribute but behind in other non-go stuff right now :(
