### ISSUE TITLE
400 instead of 422

### ISSUE THREAD

**Issue by peterbe** [mholt/binding#31]
I would prefer to use 400 Bad Request instead of 422 Unprocessable Entity when a validation of a type fails. 

The 422 is an obscure code and 400 is generally used when you supplied the parameters incorrectly which is the case of `&number=notanumber`.

**Comment by mholt** [comment]
Yeah, you're right, 422 is kind of weird. And I think it does mean something slightly different than what we think of as a "Bad Request" - and seeing as this is a general package, the more common error code should be returned.

I'll make this change eventually. Swamped with school right now, but will get around to it.

**Comment by mhemmings** [comment]
:+1:  +1 for 400: Bad Request :)

**Comment by mholt** [comment]
*sigh* I got the commit message wrong, but the code is right. 81bd1588a68d30e93c9c598098ed25be0cd0ef27

**Comment by jchannon** [comment]
hi, I always use 422, is there a way to define the status code you would like?  Happy to do a PR that is ` func (e Errors) Handle(response http.ResponseWriter, statusCode int) bool {`

**Comment by mholt** [comment]
Sure, we can see what people think.

**Comment by bhcleek** [comment]
I'd rather not do this. If you want to control the status code and error message, simply pass in an http.ResponseWriter implementation that does writes the status code you want.

**Comment by jchannon** [comment]
Do you mean write my own Handle method not pass my own ResponseWriter?

**Comment by bhcleek** [comment]
No, I mean pass your own http.ResponseWriter to `Errors.Handle`; maybe it looks something like this:

```go
type BindingErrorWriter struct {
  http.ResponseWriter
  code int
}

func (w *BindingErrorWriter) WriteHeader(code int) {
  if code > 0 {
    return
  }

  if code == 422 {
    code = 400
  }
  w.code = code
  return w.ResponseWriter.WriteHeader(code)
}
func (w *BindingErrorWriter) Write(p []byte) (int, error) {
  if w.code == 0 {
    w.WriteHeader(200)
  }
  return w.ResponseWriter.Write(p)
```
