### ISSUE TITLE
Customise error message

### ISSUE THREAD

**Issue by jchannon** [mholt/binding#39]
When you have a property that is marked as required, the error message is "Required", is there a way to add a custom message, maybe a property on the `binding.Field` struct?

Happy to do a PR if that helps so it checks if the new `ErrorMessage` property is set, if not it uses the default message

**Comment by mholt** [comment]
Yeah, this is probably doable... but there is no reason that your client needs to show the text of the error message to the user, either. Just depends if you want that logic on the server or in the client.

**Comment by jchannon** [comment]
True, but if I want to show an error message in my client I'd like a nice error message :smile:

**Comment by mholt** [comment]
Of course -- but my question is, does logic for nice client error messages belong on the server or the client?

I'm actually indifferent. It's something to think about, but you're welcome to open a PR. :)

**Comment by jchannon** [comment]
IMO its up to the server to at least give something helpful "Required" vs
"Please enter a value for Name" that can then be put into a html template
or json response. Obviously if you have custom validation you can also add
whatever message you like.

**Comment by mholt** [comment]
You can craft that on the client with the JSON response you get in the case of an error.

You get back the field name(s) the error applies to, the error classification or type ("RequiredError"), and the message, "Required" -- from there you can craft a message saying exactly what you want.

**Comment by jchannon** [comment]
Agreed thats one way.

In my experience it seems to be the case that the server validates returns the errors and the template/client just exposes whats returned :smile:

**Comment by jchannon** [comment]
Created a PR in #40
